name: Gatsby Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nix_channel:
          - "nixos-unstable"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
        with:
          nix_path: nixpkgs=channel:${{matrix.nix_channel}}
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Nix Build Base Images
        env:
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_ALGOLIA_WRITE_KEY: ${{ secrets.GATSBY_ALGOLIA_WRITE_KEY }}
          GATSBY_ALGOLIA_DRY_RUN: true
          GATSBY_ALGOLIA_CONTINUE_ON_FAILURE: true
        run: |
          nix develop --command yarn install
          nix develop --command yarn build